version: "3"

services:
  mongodb:
    restart: always
    image: mongo:5.0.0-focal
    container_name: nslab-mongo
    expose:
      - "27017"
    networks:
      - proxy
    volumes:
      - ./data:/data/db
  
  backend:
    build:
      context: ./web_src/backend
    networks:
      - proxy
    image: mingmaan/nslab-backend:latest
    container_name: nslab-backend
    expose:
      - "5000"
    environment:
      - VIRTUAL_HOST=api.netsys.skku.edu
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=api.netsys.skku.edu
      - LETSENCRYPT_EMAIL=admin@api.netsys.skku.edu
      # For nodejs dotenv module
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MDB_PORT=${MDB_PORT}
      - MONGO_URI=${MONGO_URI}

  frontend:
    build:
      context: ./web_src/frontend
    networks:
      - proxy
    image: mingmaan/nslab-frontend:latest
    container_name: nslab-frontend
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=netsys.skku.edu
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=netsys.skku.edu
      - LETSENCRYPT_EMAIL=admin@netsys.skku.edu
 
networks:
  proxy:
    external: true
